# No longer needed
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend
  namespace: petclinic
data:
 nginx.conf: |-
  pid /tmp/pid;
  error_log stderr;
  events {}
  http {
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path       /tmp/proxy_temp_path;
    fastcgi_temp_path     /tmp/fastcgi_temp;
    uwsgi_temp_path       /tmp/uwsgi_temp;
    scgi_temp_path        /tmp/scgi_temp;
    server {
      listen 8080;
      location / {
        proxy_pass http://petclinic:8080;
        proxy_http_version 1.1;
      }
    }
  }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: petclinic
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: cfg
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-conf-d
              mountPath: /etc/nginx/conf.d
            - name: nginx-tmp
              mountPath: /tmp
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
          securityContext:
            runAsUser: 1337
      volumes:
        - name: cfg
          configMap:
            name: frontend
        - name: nginx-conf-d
          emptyDir: {}
        - name: nginx-tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: petclinic
spec:
  ports:
  - name: service
    port: 8080
  selector:
    app: frontend
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: frontend
#   namespace: petclinic
#   annotations:
#     ingress.kubernetes.io/ssl-redirect: "false"
#     kubernetes.io/ingress.class: "traefik"
#     ingress.kubernetes.io/custom-request-headers: l5d-dst-override:frontend.petclinic.svc.cluster.local:8080
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: frontend
#             port:
#               number: 8080